### ISSUE TITLE
Please add some tests to show how your library is working.

### ISSUE THREAD

**Issue by vsysoev** [IlFiltsin/mind#3]

**Comment by vsysoev** [comment]
Right now there is no information how to use your library. It is very critical for library to have tests with sources to show users how to use. Please update README.md file too.

**Comment by IlFiltsin** [comment]
Hi, vsysoev. I'll add some examples of using library for next release.

**Comment by IlFiltsin** [comment]
@vsysoev 
I updated library and added examples of using it.

**Comment by vsysoev** [comment]
Solution is unacceptable. Examples, you've provided are completely useless. Most of code is input and output. You must avoid usage of stdin/stdout operations in examples or test cases, because they might be executed automatically by continuous integration tools.
